trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: 'default'
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      inputs:
        repository: self
        fetchDepth: 1
    - task: TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: 'init'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      displayName: 'terraform validate'
      inputs:
        command: 'validate'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
        command: 'plan'
        commandOptions: '-out terraform.tfplan'
        allowTelemetryCollection: true
        publishPlanResults: 'planresults.tfplan'
    - task: CopyFiles@2
      inputs:
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/Terraform'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        FileCopyOptions: ''

